[package]

name = "cui_filemanager"
version = "0.1.0"
authors = ["neruneru0419 <neruneru55555@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "*"

